# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_category_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='number',
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.CharField(default='name', max_length=255),
            preserve_default=False,
        ),
    ]
