# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 12:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_order_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='table',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='pos.Table'),
            preserve_default=False,
        ),
    ]
