# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0007_orderitem_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shopping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('status', models.BooleanField()),
                ('Notes', models.TextField()),
            ],
        ),
    ]
