# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 08:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0009_auto_20160720_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='order',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='table',
        ),
        migrations.RemoveField(
            model_name='order',
            name='table',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='table',
        ),
        migrations.RemoveField(
            model_name='product',
            name='catgory',
        ),
        migrations.DeleteModel(
            name='Shopping',
        ),
        migrations.AddField(
            model_name='table',
            name='created',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 7, 21, 8, 28, 5, 965787, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 7, 21, 8, 28, 16, 378229, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Bill',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
