# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.IntegerField(choices=[(0, 'Preparing'), (1, 'Served')], default=0),
        ),
    ]
